import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="hydrated">
      <body
        className={``}
        data-new-gr-c-s-check-loaded="14.1244.0" data-gr-ext-installed=""
      >
        {children}
      </body>
    </html>
  );
}
